backend:
  replicaCount: 1
  image:
    repository: 323336951752.dkr.ecr.ap-south-1.amazonaws.com/gitops-backend
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8000
  resources: {}
frontend:
  replicaCount: 1
  image:
    repository: 323336951752.dkr.ecr.ap-south-1.amazonaws.com/gitops-frontend
    pullPolicy: IfNotPresent
    tag: "52c0b01cd1c79dd3676facfa4fa28786022434a3"
  service:
    type: LoadBalancer
    port: 80
  resources: {}
