apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitops-app.fullname" . }}-frontend
  labels:
    app: {{ include "gitops-app.name" . }}-frontend
    chart: {{ include "gitops-app.chart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gitops-app.name" . }}-frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "gitops-app.name" . }}-frontend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
